### ISSUE TITLE
Public?

### ISSUE THREAD

**Issue by rad4day** [dimsumlabs/dsl-accounts-scans#1]
This isn't supposed to be public, is it?

**Comment by hamishcoleman** [comment]
sure is!  The running of the space is no secret and none of the bills or receipts should be a surprise to members (or potential members) and the best way to achieve that is to have the books in the open.

These files have all been publicly visible in the https://github.com/dimsumlabs/dsl-accounts repository for some time and I simply factored them out into their own repo this afternoon
